version: '3.4'

services:
  webapi2:
    image: ${DOCKER_REGISTRY-}webapi2
    build:
      context: .
      dockerfile: WebAPI2/Dockerfile


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: